import type { SectorScoreType, AnomalyEventType } from 'shared-types';

const now = new Date().toISOString();

export const MOCK_SCORES: SectorScoreType[] = [
  {
    sector: 'BANKING',
    score: 74,
    traffic_light: 'green',
    beginner_label: 'Institutional buy pressure',
    signal_breakdown: {
      fii_net_cr: 3200,
      dii_net_cr: 1800,
      pcr: 1.12,
      block_deal_net_cr: 420,
      mf_inflow_cr: 950,
      data_completeness: 5,
    },
    computed_at: now,
    run_window: 'closing',
    is_partial: false,
  },
  {
    sector: 'IT',
    score: 38,
    traffic_light: 'red',
    beginner_label: 'Institutional sell pressure',
    signal_breakdown: {
      fii_net_cr: -4100,
      dii_net_cr: 600,
      pcr: 0.58,
      block_deal_net_cr: -310,
      mf_inflow_cr: 200,
      data_completeness: 5,
    },
    computed_at: now,
    run_window: 'closing',
    is_partial: false,
  },
  {
    sector: 'ENERGY',
    score: 62,
    traffic_light: 'green',
    beginner_label: 'Institutional buy pressure',
    signal_breakdown: {
      fii_net_cr: 1400,
      dii_net_cr: 900,
      pcr: 1.05,
      block_deal_net_cr: 180,
      mf_inflow_cr: 550,
      data_completeness: 5,
    },
    computed_at: now,
    run_window: 'closing',
    is_partial: false,
  },
  {
    sector: 'AUTO',
    score: 51,
    traffic_light: 'amber',
    beginner_label: 'Mixed institutional signals',
    signal_breakdown: {
      fii_net_cr: -800,
      dii_net_cr: 1200,
      pcr: 0.95,
      block_deal_net_cr: null,
      mf_inflow_cr: 300,
      data_completeness: 4,
    },
    computed_at: now,
    run_window: 'closing',
    is_partial: false,
  },
  {
    sector: 'FMCG',
    score: 45,
    traffic_light: 'amber',
    beginner_label: 'Mixed institutional signals',
    signal_breakdown: {
      fii_net_cr: -1200,
      dii_net_cr: 1500,
      pcr: 0.82,
      block_deal_net_cr: 90,
      mf_inflow_cr: null,
      data_completeness: 4,
    },
    computed_at: now,
    run_window: 'closing',
    is_partial: false,
  },
  {
    sector: 'PHARMA',
    score: 33,
    traffic_light: 'red',
    beginner_label: 'Institutional sell pressure',
    signal_breakdown: {
      fii_net_cr: -2800,
      dii_net_cr: 400,
      pcr: 0.61,
      block_deal_net_cr: -150,
      mf_inflow_cr: null,
      data_completeness: 3,
    },
    computed_at: now,
    run_window: 'closing',
    is_partial: true,
  },
  {
    sector: 'METALS',
    score: 68,
    traffic_light: 'green',
    beginner_label: 'Institutional buy pressure',
    signal_breakdown: {
      fii_net_cr: 2100,
      dii_net_cr: 700,
      pcr: 1.35,
      block_deal_net_cr: 600,
      mf_inflow_cr: 280,
      data_completeness: 5,
    },
    computed_at: now,
    run_window: 'closing',
    is_partial: false,
  },
];

export const MOCK_ANOMALIES: AnomalyEventType[] = [
  {
    sector: 'IT',
    anomaly_type: 'consecutive_fii_sell',
    severity: 'HIGH',
    raw_data: { streak_length: 4, total_outflow_cr: -12400, sector: 'IT' },
    alert_text: 'FII net equity in IT has been negative for 4 consecutive sessions, totalling -\u20B912,400 Cr.',
    historical_context: 'In the last 12 months, IT experienced 2 similar FII sell streaks of 4+ sessions. On both occasions, the streak ended within 2 further sessions. Past patterns do not predict future outcomes.',
    disclaimer: 'This alert describes historical data patterns. It is not financial advice. Past patterns do not predict future outcomes. Niftea is not a SEBI-registered investment adviser.',
    detected_at: now,
  },
  {
    sector: 'PHARMA',
    anomaly_type: 'pcr_threshold_breach',
    severity: 'HIGH',
    raw_data: { pcr: 0.61, threshold: 'below 0.65', sector: 'PHARMA' },
    alert_text: 'Put-Call Ratio for PHARMA has dropped to 0.61, breaching the 0.65 lower threshold.',
    historical_context: 'Insufficient historical data to establish a pattern. Past patterns do not predict future outcomes.',
    disclaimer: 'This alert describes historical data patterns. It is not financial advice. Past patterns do not predict future outcomes. Niftea is not a SEBI-registered investment adviser.',
    detected_at: now,
  },
  {
    sector: 'METALS',
    anomaly_type: 'large_block_deal',
    severity: 'MEDIUM',
    raw_data: { deal_value_cr: 600, sector: 'METALS', deal_type: 'buy' },
    alert_text: 'A block deal of \u20B9600 Cr (buy) was recorded in the METALS sector this session.',
    disclaimer: 'This alert describes historical data patterns. It is not financial advice. Past patterns do not predict future outcomes. Niftea is not a SEBI-registered investment adviser.',
    detected_at: now,
  },
];
